name: flutter_master_extensions
description: "Set of method-extensions for dart that makes using framework in a much easier and clean way also adds additional functionality."
version: 0.0.1
homepage: https://github.com/BhaumikDK/flutter_master_extensions.git

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter Common Utils  
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  # Iterable Partitions
  quiver: ^3.2.2
  # Google Fonts
  google_fonts: ^6.2.1
  # Remote Config
  http: ^1.3.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0